### ISSUE TITLE
ECONNRESETでプロセスが落ちる

### ISSUE THREAD

**Issue by tanaka0x** [realglobe-Inc/v-cloud#3]
クライアント側がwebsocketの終了手順を正しく行わない場合にRSTパケットが送られ、アプリケーションが終了してしまう

```
% PATH=$PATH:$(pwd)/node_modules/.bin $(yarn bin)/pon debug
[env:debug] Task started...

[env:debug] =========================================
[env:debug]  DEBUG: "undefined" -> "app:*"
[env:debug]  NODE_ENV: "undefined" -> "development"
[env:debug] =========================================

[env:debug] ...done! (4ms)

[debug:server] Task started...
=============================

V Cloud listening on port 7001

=============================
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
[debug:server] ...done! (12691ms)
```

**Comment by tanaka0x** [comment]
v-spot-wsにエラーハンドラを追加すれば落ちなくなるみたいです

```js
// VSpotWSServer.js
// ...

wsProxy(ws, {
  // ...
})

ws.on('error', async function onError (e) {
  debug('error', e)
  connector.disconnect()
})

ws.on('close', async function onClose () {
  // ...
})

// ...
```

**Comment by okunishinishi** [comment]
PR大歓迎
